version: '3.8'

services:
  nginx:
    build: requirements/nginx/
    container_name: nginx
    image: nginx
    volumes:
      - "wordpress-volume:/var/www/wordpress"
    ports:
      - "443:443"
    networks:
      - inception
    depends_on:
      - wordpress
    restart: always

  mariadb:
    build: requirements/mariadb/
    container_name: mariadb
    image: mariadb
    volumes:
      - "mariadb-volume:/var/lib/mysql"
    networks:
      - inception
    environment:
      MYSQL_ROOT_PWD: ${MYSQL_ROOT_PWD}
      WP_DB_NAME:     ${WP_DB_NAME}
      WP_DB_USR:      ${WP_DB_USR}
      WP_DB_PWD:      ${WP_DB_PWD}
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "${WP_DB_USR}", "-p${WP_DB_PWD}"]
      timeout: 1s
      retries: 50
    restart: always
  
  wordpress:
    build: requirements/wordpress/
    container_name: wordpress
    image: wordpress
    volumes:
      - "wordpress-volume:/var/www/wordpress"
    networks:
      - inception
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      MYSQL_HOST:     ${MYSQL_HOST}
      WP_DB_NAME:     ${WP_DB_NAME}
      WP_DB_USR:      ${WP_DB_USR}
      WP_DB_PWD:      ${WP_DB_PWD}
      DOMAIN_NAME:    ${DOMAIN_NAME}
      WP_TITLE:       ${WP_TITLE}
      WP_ADMIN_USR:   ${WP_ADMIN_USR}
      WP_ADMIN_PWD:   ${WP_ADMIN_PWD}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_USR:         ${WP_USR}
      WP_PWD:         ${WP_PWD}
      WP_EMAIL:       ${WP_EMAIL}
    restart: always

volumes:
  mariadb-volume:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${MARIADB_HOST_VOLUME_PATH}

  wordpress-volume:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${WORDPRESS_HOST_VOLUME_PATH}

networks:
  inception:
    driver: bridge
    name: inception
